#!/bin/sh
alias _is_run='!(return 0 2>/dev/null)'

if _is_run; then
    SCRIPTS_DIR=$(dirname "$(realpath "$0")")
else
    if [ -z "${SCRIPTS_DIR:-}" ]; then
        echo "ERROR: If sourced and not run, SCRIPTS_DIR env var must contain the path to scripts directory" >&2
        return 1  # sourced
    fi
fi

ROOT_DIR=$(realpath "$SCRIPTS_DIR/..")


# == Main function
function for_each_component()
{
    command="$@"

    cd "$ROOT_DIR"
    for comp_dir in $(find components -d -maxdepth 1 -mindepth 1); do
        echo "./$comp_dir"
        (
            cd "$comp_dir"
            $command
        )
    done
}

if _is_run; then
    for_each_component "$@"
fi
