#!/bin/sh
(return 0 2>/dev/null) && {
    echo "ERROR: This script cannot be sourced. It must be run." >&2
    return 1
}

SCRIPTS_DIR=$(dirname "$(realpath "$0")")
ROOT_DIR=$(realpath "$SCRIPTS_DIR/..")


# == Main function
function for_each_component()
{
    command="$@"

    cd "$ROOT_DIR"
    for comp_dir in $(find components -d -maxdepth 1 -mindepth 1); do
        echo "./$comp_dir"
        (
            cd "$comp_dir"
            $command
        )
    done
}


for_each_component "$@"
